# Generated by Django 5.0.6 on 2024-06-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_booking_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
    ]
