# Generated by Django 5.0.6 on 2024-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_booking_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
