# Generated by Django 5.0.6 on 2024-06-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_alter_booking_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
    ]
